### ISSUE TITLE
Assembly methodology question

### ISSUE THREAD

**Issue by lincoln-harris** [Teichlab/tracer#71]
Hi there
In your online methods you state 'we used custom python scripts to compare the recombinant identifiers present in each cell to find cases where multiple cells contained the same identifier.' Presumably this means V and J gene names were compared, *ie.* the first and third parts of the example identifying string `TRBV31_AGTCTTGACACAAGA_TRBJ2-5`. Im wondering if the junctional nucleotide sequence was used for this comparison as well?
Lincoln Harris

**Comment by mstubb** [comment]
Yes, the junctional nucleotide sequence was compared as well. Cells are inferred to be clonal related if the TCR sequences exactly match and don’t just share V and J genes. 

Mike

**Comment by lincoln-harris** [comment]
Awesome! Thanks. As a follow-up, it doesn't look like the D segments are assembled for the B chain. Why is that?

**Comment by mstubb** [comment]
The D segments are assembled (because they’re part of the sequence) but we don’t attempt to annotate them because they’re so short and often chewed back so much by the exonuclease activity of RAG that it’s not possible to usefully annotate them with a segment. The nucleotides derived from the D segments will form part of the junctional identifier though.
