### ISSUE TITLE
version of TraCeR in docker container 

### ISSUE THREAD

**Issue by orrzor** [Teichlab/tracer#99]
Hi Michael,

I hope you are doing well! 

Can you please let me know what version of TraCeR is in the docker container on docker hub? I assume it's the latest version, 0.6.0, but was having trouble verifying this was the case. Thanks for your help -Orr

**Comment by mstubb** [comment]
Hi Orr,

That's frustratingly hard to find out. 

I think we had tried to get Dockerhub set up so that it rebuilt the image after every commit to master. However, I seem to remember that being a bit flaky. Would it be helpful for me to kick off a rebuild to make a new image based on the latest master? Happy to do that, so let me know.

Cheers,

Mike

**Comment by orrzor** [comment]
Hi Mike,

Thanks for getting back to me! I would really appreciate it if you could make a rebuild with the newest image. I have short reads so I really would like to be sure I am using v0.6.0. It's no rush, and I really appreciate you maintaining this very useful software!

All the best and thank you, Orr

**Comment by mstubb** [comment]
Hi Orr,

I took a brief trip into dependency hell (😉) but I've now rebuilt the image in Dockerhub using the most up to date version of `master`. 

It seems to work ok with the test data. Feel free to reopen this issue if you have any problems.

Thanks!

Mike

**Comment by orrzor** [comment]
Hi Mike,

I can't tell you how much I appreciate it! I had tried to get TraCeR going again through local install but also had dependency issues. Then I switched to the Docker. Thank you so much for making a container with the latest code!

Best, Orr
